### ISSUE TITLE
Status not showing

### ISSUE THREAD

**Issue by busby666** [e-m-b-a/emba#1334] opened 2024-10-11 08:49 UTC
Using the latest version of both Kali and EMBA.

I had started an Analysis with 8 CPU and about 12GB of memory.  Sometime during the night system seemed to freeze so I forced a restart of the VM.

Once the system came up I was able to verify that the virtual disk was not full; still had 16GB left.

So I started the Analysis again but did not clear the LOG directory and tried to resume the analysis. Everything seemed to start fine. I did see task P99_prepare_analyzer again and that seemed to finish and right now the analysis is proceeding.

But noticed a minor issue at the bottom of the screen.  All of the status boxes are not populated and refreshing.  Not a major issue by any means.
![2024-10-11_03-48-11](https://github.com/user-attachments/assets/424a0c34-7047-40ed-b5bc-0b04a4aa1a51)

**Comment by m-1-k-3** [comment] 2024-10-11 08:54
Thank you for reporting. Yea ... the restart feature is somehow not fully stable. I need to check on this soon

**Comment by busby666** [comment] 2024-10-11 09:54
I will try and do what I can to help I can certainly code but I am old C programmer.  However; I can code in most languages if I put my mind too it.  Just want to participate.  Maybe I can start with docs and notes.

**Comment by busby666** [comment] 2024-10-11 13:34
I seeing another odd issue but unable right now to gather information that would aid anyone in determining the problem.  VM just becomes unusable.

**Comment by m-1-k-3** [comment] 2024-10-18 08:49
I tried to reproduce this issue but for me it looks as it recovers the boxes quite good:

![image](https://github.com/user-attachments/assets/900abfe7-eaeb-4733-b1b9-820c1deb340f)

Could you please reproduce it on your side and give me step by step instructions?

**Comment by torabi12** [comment] 2024-10-24 07:21
I checked also and it works for me on Kali:

![image](https://github.com/user-attachments/assets/c9e4b4cb-de57-4793-a0e3-6ec6dece078c)

**Comment by m-1-k-3** [comment] 2024-11-01 08:26
Any updates on this? Otherwise I would close it.

**Comment by busby666** [comment] 2024-11-01 14:54
I think I closed it can you confirm?

**Closed** 2024-11-01 15:28 UTC
Labels: bug, can't reproduce, EMBA
